# Generated by Django 5.0.6 on 2024-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
