# Generated by Django 5.0.6 on 2024-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0003_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techteam',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='techteam',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techteam',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
