# Generated by Django 5.0.6 on 2024-08-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0004_rename_name_techteam_first_name_techteam_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techteam',
            name='username',
        ),
    ]
