# Generated by Django 5.0.6 on 2024-08-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0005_remove_techteam_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills_required',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
