# Generated by Django 5.0.6 on 2024-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0007_project_assigned_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='techteam',
            name='assigned_work',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
