# Generated by Django 5.0.6 on 2024-08-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0007_client_manager_techteam_approval_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelancer',
            new_name='User',
        ),
    ]
