# Generated by Django 5.0.6 on 2024-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0008_techteam_assigned_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.TextField(),
        ),
    ]
