# Generated by Django 5.0.6 on 2024-09-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0009_alter_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills_required',
            field=models.JSONField(default=list, null=True),
        ),
    ]
