# Generated by Django 5.0.6 on 2024-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0012_project_assigned_with_project_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techteam',
            name='assigned_work',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
