# Generated by Django 5.0.6 on 2024-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0013_alter_techteam_assigned_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_with',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_with', to='TriplesTalent_App.freelancer'),
        ),
    ]
