# Generated by Django 5.0.6 on 2024-09-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriplesTalent_App', '0014_remove_project_assigned_with_project_assigned_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=50),
        ),
    ]
